apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python

resources:
  - ./core/namespace.yaml
  # - ./core/pv.yaml
  # - ./core/deployment-db.yaml
  # - .//core/deployment-backend.yaml
  # - ./core/deployment-frontend.yaml
  - ./core/deployment.yaml
  - ./core/service.yaml
  - ./core/ingress.yaml
  - ./core/cronjobs.yaml