---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fetch-datetime-from-web
  namespace: python
spec:
  jobTemplate:
    metadata:
      name: fetch-datetime-from-web
    spec:
      template:
        spec:
          containers:
          - image: pythonStarter
            name: fetch-datetime-from-web
            env:
            - name: IN_CLUSTER
              value: "1"
            resources: {}
            command:
              - python3
              - cron.py
          restartPolicy: OnFailure
  schedule: '* * * * *'

  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5